-- Multi-provider support: record which vendor + model served each turn, and
-- lock a conversation to the provider that started it.
CREATE TYPE "public"."ai_provider" AS ENUM('anthropic', 'openai', 'google');--> statement-breakpoint
ALTER TABLE "conversation_messages" ADD COLUMN "provider" "ai_provider";--> statement-breakpoint
ALTER TABLE "conversation_messages" ADD COLUMN "model" text;--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "provider" "ai_provider";--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "tier" text;--> statement-breakpoint

-- Backfill: every transcript that exists today was generated by Claude, since
-- Anthropic was the only provider. Recording that keeps history truthful
-- rather than leaving it ambiguously null. Only ASSISTANT turns get a
-- provider — user turns aren't generated by anyone.
UPDATE "conversation_messages"
   SET "provider" = 'anthropic'
 WHERE "role" = 'assistant' AND "provider" IS NULL;--> statement-breakpoint

-- Lock pre-existing conversations to Anthropic: they contain Anthropic-shaped
-- tool_use blocks and Anthropic-issued call ids that the owner's stored
-- decisions are keyed on.
UPDATE "conversations" c
   SET "provider" = 'anthropic'
 WHERE "provider" IS NULL
   AND EXISTS (
     SELECT 1 FROM "conversation_messages" m
      WHERE m."conversation_id" = c."id" AND m."role" = 'assistant'
   );
